services:
  db:
    env_file:
      - ./.env
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - potluck-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  potluck-pgdata:
