services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=potluck
      - POSTGRES_PASSWORD=potluck
    volumes:
      - potluck-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  potluck-pgdata:
